-- AlterTable
ALTER TABLE "Bet" ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'PENDING',
ALTER COLUMN "outcome" DROP NOT NULL,
ALTER COLUMN "result" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "balance" DOUBLE PRECISION NOT NULL DEFAULT 0;
