// backend/src/routes/bet.js
const express = require("express");
const router = express.Router();
const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

// POST route for creating a bet with match upsert
router.post("/", async (req, res) => {
  const { wallet, matchId, betChoice, amount, outcome, result } = req.body;
  if (!wallet || !matchId || !betChoice || !amount || !outcome) {
    return res.status(400).json({ error: "Missing required bet fields" });
  }
  try {
    // Find the user by wallet
    const user = await prisma.user.findUnique({ where: { wallet } });
    if (!user) {
      return res.status(404).json({ error: "User not found" });
    }

    // Check if the match exists
    let match = await prisma.match.findUnique({
      where: { id: parseInt(matchId) },
    });
    if (!match) {
      // Create a new match record using default or provided details
      match = await prisma.match.create({
        data: {
          id: parseInt(matchId),
          title: `Match ${matchId}`,
          description: "Auto-created match",
          startTime: new Date(),
          status: "upcoming",
        },
      });
    }

    // If match not found, create one (you can customize these values)
    if (!match) {
      match = await prisma.match.create({
        data: {
          // Note: The 'id' field is auto-generated by default.
          // If you want to force a specific id, you need to adjust your Prisma schema.
          title: `Match ${matchId}`,
          description: "Auto-generated match record for testing",
          startTime: new Date(), // or a provided value
          status: "upcoming",
        },
      });
    }

    // Create a new bet record in the database
    const newBet = await prisma.bet.create({
      data: {
        userId: user.id,
        matchId: match.id,
        betChoice,
        amount: parseFloat(amount),
        outcome,
        result: parseFloat(result),
      },
    });
    res.status(201).json(newBet);
  } catch (error) {
    console.error("Error creating bet:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

// GET route remains unchanged...
router.get("/", async (req, res) => {
  const { wallet } = req.query;
  if (!wallet) return res.status(400).json({ error: "Wallet is required" });
  try {
    const user = await prisma.user.findUnique({ where: { wallet } });
    if (!user) return res.status(404).json({ error: "User not found" });
    const bets = await prisma.bet.findMany({
      where: { userId: user.id },
      orderBy: { timestamp: "desc" },
    });
    res.json({ bets });
  } catch (error) {
    console.error("Error fetching bet history:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

module.exports = router;
